GSETTINGS_SCHEMA_DIR="/opt/homebrew/opt/glib/share/glib-2.0/schemas"
XDG_DATA_DIRS="/opt/homebrew/share"
DARKTABLE_BIN="/Users/draco892/bin/darktable-dev/bin/darktable"
DARKTABLE_CONFIG_DIR="/Users/draco892/bin/darktable-dev/.config/darktable"
DARKTABLE_CACHE_DIR="/Users/draco892/bin/darktable-dev/.cache/darktable"